-- blog/migrations/0003_comment_...py
-- （Django 的 0002_alter_post_slug 只是给 slug 加了 unique_for_date，那是表单层校验，不改表结构，所以这里没有对应脚本）
CREATE TABLE blog_comment (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  BIGINT       NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    name     VARCHAR(80)  NOT NULL,
    email    VARCHAR(254) NOT NULL,
    body     TEXT         NOT NULL,
    created  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated  TIMESTAMP WITH TIME ZONE NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX blog_comment_created_idx ON blog_comment (created);
CREATE INDEX blog_comment_post_id_idx ON blog_comment (post_id);
