-- courses/migrations/0001_initial.py 与 0002_video_text_image_file_content.py
CREATE TABLE courses_subject (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(200) NOT NULL,
    slug   VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE courses_course (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    subject_id  BIGINT       NOT NULL REFERENCES courses_subject (id) ON DELETE CASCADE,
    title       VARCHAR(200) NOT NULL,
    slug        VARCHAR(200) NOT NULL UNIQUE,
    overview    TEXT         NOT NULL,
    created     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX courses_course_owner_id_idx ON courses_course (owner_id);
CREATE INDEX courses_course_subject_id_idx ON courses_course (subject_id);

-- "order" 是 SQL 关键字，必须加引号
CREATE TABLE courses_module (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    BIGINT       NOT NULL REFERENCES courses_course (id) ON DELETE CASCADE,
    title        VARCHAR(200) NOT NULL,
    description  TEXT         NOT NULL DEFAULT '',
    "order"      INTEGER      NOT NULL CHECK ("order" >= 0)
);
CREATE INDEX courses_module_course_id_idx ON courses_module (course_id);

-- 继承体系的公共表（JOINED 策略）：item_type 是区分子类的“鉴别列”
CREATE TABLE courses_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type  VARCHAR(20)  NOT NULL,
    owner_id   BIGINT       NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    title      VARCHAR(250) NOT NULL,
    created    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX courses_item_owner_id_idx ON courses_item (owner_id);

-- 子类各一张表，主键同时是指向 courses_item 的外键
CREATE TABLE courses_text  (item_id BIGINT PRIMARY KEY REFERENCES courses_item (id) ON DELETE CASCADE, content TEXT NOT NULL);
CREATE TABLE courses_file  (item_id BIGINT PRIMARY KEY REFERENCES courses_item (id) ON DELETE CASCADE, file VARCHAR(200) NOT NULL);
CREATE TABLE courses_image (item_id BIGINT PRIMARY KEY REFERENCES courses_item (id) ON DELETE CASCADE, file VARCHAR(200) NOT NULL);
CREATE TABLE courses_video (item_id BIGINT PRIMARY KEY REFERENCES courses_item (id) ON DELETE CASCADE, url VARCHAR(200) NOT NULL);

-- 与 Django 的 GenericForeignKey 不同，item_id 是真正的外键
CREATE TABLE courses_content (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id  BIGINT  NOT NULL REFERENCES courses_module (id) ON DELETE CASCADE,
    item_id    BIGINT  NOT NULL UNIQUE REFERENCES courses_item (id) ON DELETE CASCADE,
    "order"    INTEGER NOT NULL CHECK ("order" >= 0)
);
CREATE INDEX courses_content_module_id_idx ON courses_content (module_id);
