-- account/migrations/0001_initial.py：Profile 与 User 一对一
CREATE TABLE account_profile (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL UNIQUE REFERENCES auth_user (id) ON DELETE CASCADE,
    date_of_birth  DATE,
    photo          VARCHAR(100) NOT NULL DEFAULT ''
);
