-- ≈ python-social-auth 的 social_auth_usersocialauth 表
CREATE TABLE social_auth_usersocialauth (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT       NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    provider  VARCHAR(32)  NOT NULL,
    uid       VARCHAR(255) NOT NULL,
    created   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT social_auth_provider_uid_uniq UNIQUE (provider, uid)
);

CREATE INDEX social_auth_user_id_idx ON social_auth_usersocialauth (user_id);
