-- account/migrations/0002_contact.py：关注关系（Django 版没有唯一约束，这里加上，防止重复关注）
CREATE TABLE account_contact (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_from_id  BIGINT NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    user_to_id    BIGINT NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    created       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT account_contact_from_to_uniq UNIQUE (user_from_id, user_to_id)
);

CREATE INDEX account_contact_created_idx ON account_contact (created DESC);
CREATE INDEX account_contact_user_to_id_idx ON account_contact (user_to_id);
