-- actions/migrations/0001_initial.py
-- target_type + target_id 是“泛型外键”：数据库无法给它建外键约束，目标被删除后这里会留下悬空引用
CREATE TABLE actions_action (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    verb         VARCHAR(255) NOT NULL,
    created      TIMESTAMP WITH TIME ZONE NOT NULL,
    target_type  VARCHAR(50),
    target_id    BIGINT
);

CREATE INDEX actions_action_created_idx ON actions_action (created DESC);
CREATE INDEX actions_action_target_idx ON actions_action (target_type, target_id);
CREATE INDEX actions_action_user_id_idx ON actions_action (user_id);
