-- django.contrib.auth 的用户、组、组权限（权限简化为代码字符串）
CREATE TABLE auth_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(150) NOT NULL UNIQUE,
    password      VARCHAR(128) NOT NULL,
    first_name    VARCHAR(150) NOT NULL DEFAULT '',
    last_name     VARCHAR(150) NOT NULL DEFAULT '',
    email         VARCHAR(254) NOT NULL DEFAULT '',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    is_staff      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_superuser  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login    TIMESTAMP WITH TIME ZONE,
    date_joined   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_group (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE auth_group_permissions (
    group_id  BIGINT       NOT NULL REFERENCES auth_group (id) ON DELETE CASCADE,
    codename  VARCHAR(100) NOT NULL,
    PRIMARY KEY (group_id, codename)
);

CREATE TABLE auth_user_groups (
    user_id   BIGINT NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    group_id  BIGINT NOT NULL REFERENCES auth_group (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, group_id)
);
