CREATE TABLE auth_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(150) NOT NULL UNIQUE,
    password      VARCHAR(128) NOT NULL,
    first_name    VARCHAR(150) NOT NULL DEFAULT '',
    last_name     VARCHAR(150) NOT NULL DEFAULT '',
    email         VARCHAR(254) NOT NULL DEFAULT '',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    is_staff      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_superuser  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login    TIMESTAMP WITH TIME ZONE,
    date_joined   TIMESTAMP WITH TIME ZONE NOT NULL
);
