-- images/migrations/0001_initial.py
CREATE TABLE images_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    title        VARCHAR(200)  NOT NULL,
    slug         VARCHAR(200)  NOT NULL,
    url          VARCHAR(2000) NOT NULL,
    image        VARCHAR(100)  NOT NULL,
    description  TEXT          NOT NULL DEFAULT '',
    created      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX images_image_created_idx ON images_image (created DESC);
CREATE INDEX images_image_user_id_idx ON images_image (user_id);
CREATE INDEX images_image_slug_idx ON images_image (slug);

-- users_like = ManyToManyField(...)：Django 自动生成的中间表
CREATE TABLE images_image_users_like (
    image_id  BIGINT NOT NULL REFERENCES images_image (id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    PRIMARY KEY (image_id, user_id)
);

CREATE INDEX images_image_users_like_user_id_idx ON images_image_users_like (user_id);
