-- chat.Message：on_delete=PROTECT → 外键不级联（有聊天记录的用户、课程不能直接删除）
CREATE TABLE chat_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES auth_user (id),
    course_id  BIGINT NOT NULL REFERENCES courses_course (id),
    content    TEXT   NOT NULL,
    sent_on    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX chat_message_course_idx ON chat_message (course_id, id);
