-- Flyway 迁移脚本 ≈ Django 的 migrations/0001_initial.py。
-- 区别：Django 根据模型自动生成迁移；Flyway 需要手写 SQL，文件名里的 V1、V2 决定执行顺序。
CREATE TABLE auth_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(150) NOT NULL UNIQUE,
    password      VARCHAR(128) NOT NULL,
    email         VARCHAR(254) NOT NULL DEFAULT '',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    is_staff      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_superuser  BOOLEAN      NOT NULL DEFAULT FALSE,
    date_joined   TIMESTAMP WITH TIME ZONE NOT NULL
);
