-- shop/migrations/0001_initial.py
CREATE TABLE shop_category (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(200) NOT NULL,
    slug  VARCHAR(200) NOT NULL UNIQUE
);
CREATE INDEX shop_category_name_idx ON shop_category (name);

CREATE TABLE shop_product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT         NOT NULL REFERENCES shop_category (id) ON DELETE CASCADE,
    name         VARCHAR(200)   NOT NULL,
    slug         VARCHAR(200)   NOT NULL,
    image        VARCHAR(100)   NOT NULL DEFAULT '',
    description  TEXT           NOT NULL DEFAULT '',
    price        NUMERIC(10, 2) NOT NULL,
    available    BOOLEAN        NOT NULL DEFAULT TRUE,
    created      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX shop_product_id_slug_idx ON shop_product (id, slug);
CREATE INDEX shop_product_name_idx ON shop_product (name);
CREATE INDEX shop_product_created_idx ON shop_product (created DESC);
CREATE INDEX shop_product_category_id_idx ON shop_product (category_id);
