-- coupons/migrations/0001_initial.py
CREATE TABLE coupons_coupon (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL UNIQUE,
    valid_from  TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to    TIMESTAMP WITH TIME ZONE NOT NULL,
    discount    INTEGER     NOT NULL CHECK (discount BETWEEN 0 AND 100),   -- Django 的校验器只在表单层生效，这里让数据库也检查
    active      BOOLEAN     NOT NULL
);
