-- ≈ 书中为 django-parler 做的三步迁移：
--   ① 创建翻译表  ② 数据迁移：把原来的 name/slug/description 复制成英文译文  ③ 删除原来的列
CREATE TABLE shop_category_translation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id      BIGINT       NOT NULL REFERENCES shop_category (id) ON DELETE CASCADE,
    language_code  VARCHAR(15)  NOT NULL,
    name           VARCHAR(200) NOT NULL,
    slug           VARCHAR(200) NOT NULL,
    CONSTRAINT shop_category_translation_lang_master_uniq UNIQUE (language_code, master_id),
    CONSTRAINT shop_category_translation_lang_slug_uniq UNIQUE (language_code, slug)
);

CREATE TABLE shop_product_translation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id      BIGINT       NOT NULL REFERENCES shop_product (id) ON DELETE CASCADE,
    language_code  VARCHAR(15)  NOT NULL,
    name           VARCHAR(200) NOT NULL,
    slug           VARCHAR(200) NOT NULL,
    description    TEXT         NOT NULL DEFAULT '',
    CONSTRAINT shop_product_translation_lang_master_uniq UNIQUE (language_code, master_id)
);
CREATE INDEX shop_product_translation_slug_idx ON shop_product_translation (slug);

INSERT INTO shop_category_translation (master_id, language_code, name, slug)
SELECT id, 'en', name, slug FROM shop_category;

INSERT INTO shop_product_translation (master_id, language_code, name, slug, description)
SELECT id, 'en', name, slug, description FROM shop_product;

DROP INDEX shop_category_name_idx;
ALTER TABLE shop_category DROP COLUMN name;
ALTER TABLE shop_category DROP COLUMN slug;

DROP INDEX shop_product_id_slug_idx;
DROP INDEX shop_product_name_idx;
ALTER TABLE shop_product DROP COLUMN name;
ALTER TABLE shop_product DROP COLUMN slug;
ALTER TABLE shop_product DROP COLUMN description;
