-- blog/migrations/0001_initial.py
CREATE TABLE blog_post (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(250) NOT NULL,
    slug       VARCHAR(250) NOT NULL,
    author_id  BIGINT       NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    body       TEXT         NOT NULL,
    publish    TIMESTAMP WITH TIME ZONE NOT NULL,
    created    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated    TIMESTAMP WITH TIME ZONE NOT NULL,
    status     VARCHAR(2)   NOT NULL DEFAULT 'DF'
);

-- Meta.indexes = [models.Index(fields=['-publish'])]
CREATE INDEX blog_post_publish_idx ON blog_post (publish DESC);
-- Django 会自动给外键建索引，手写 SQL 时别忘了
CREATE INDEX blog_post_author_id_idx ON blog_post (author_id);
-- Django 的 SlugField 默认带 db_index=True
CREATE INDEX blog_post_slug_idx ON blog_post (slug);
