-- blog/migrations/0004_post_tags.py（django-taggit 用的是通用的 taggit_tag / taggit_taggeditem 两张表，这里简化为普通多对多）
CREATE TABLE blog_tag (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL UNIQUE,
    slug  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE blog_post_tags (
    post_id  BIGINT NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES blog_tag (id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

CREATE INDEX blog_post_tags_tag_id_idx ON blog_post_tags (tag_id);
