-- orders/migrations/0001_initial.py
CREATE TABLE orders_order (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    email        VARCHAR(254) NOT NULL,
    address      VARCHAR(250) NOT NULL,
    postal_code  VARCHAR(20)  NOT NULL,
    city         VARCHAR(100) NOT NULL,
    created      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated      TIMESTAMP WITH TIME ZONE NOT NULL,
    paid         BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX orders_order_created_idx ON orders_order (created DESC);

CREATE TABLE orders_orderitem (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT         NOT NULL REFERENCES orders_order (id) ON DELETE CASCADE,
    product_id  BIGINT         NOT NULL REFERENCES shop_product (id) ON DELETE CASCADE,
    price       NUMERIC(10, 2) NOT NULL,
    quantity    INTEGER        NOT NULL DEFAULT 1 CHECK (quantity >= 0)   -- PositiveIntegerField
);
CREATE INDEX orders_orderitem_order_id_idx ON orders_orderitem (order_id);
CREATE INDEX orders_orderitem_product_id_idx ON orders_orderitem (product_id);
